defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
        # [entryPoints.http.redirect]
        # entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    compress = false
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            certFile = "/etc/traefik/nip/server.crt"
            keyFile = "/etc/traefik/nip/server.key"
  [entryPoints.traefik]
    address = ":8080"

[api]
    entryPoint = "traefik"
    dashboard = true
    insecure = true

[docker]
    watch = true
    exposedByDefault = false
    network = "reverse-proxy"
